[2025-02-18T19:04:35.207+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-02-18T19:04:33.581267+00:00 [queued]>
[2025-02-18T19:04:35.222+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-02-18T19:04:33.581267+00:00 [queued]>
[2025-02-18T19:04:35.224+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-02-18T19:04:35.247+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): extract> on 2025-02-18 19:04:33.581267+00:00
[2025-02-18T19:04:35.252+0000] {standard_task_runner.py:57} INFO - Started process 201 to run task
[2025-02-18T19:04:35.257+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract', 'manual__2025-02-18T19:04:33.581267+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpiv46q60f']
[2025-02-18T19:04:35.260+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask extract
[2025-02-18T19:04:35.287+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:188 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-18T19:04:35.351+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_pipeline.extract manual__2025-02-18T19:04:33.581267+00:00 [running]> on host ff42797578c0
[2025-02-18T19:04:35.472+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T19:04:33.581267+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T19:04:33.581267+00:00'
[2025-02-18T19:04:35.474+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-02-18T19:04:35.476+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "üîç Iniciando extracci√≥n de datos..." && sleep 2 && echo "‚úÖ Extracci√≥n completada."']
[2025-02-18T19:04:35.485+0000] {subprocess.py:86} INFO - Output:
[2025-02-18T19:04:35.487+0000] {subprocess.py:93} INFO - üîç Iniciando extracci√≥n de datos...
[2025-02-18T19:04:37.489+0000] {subprocess.py:93} INFO - ‚úÖ Extracci√≥n completada.
[2025-02-18T19:04:37.490+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-02-18T19:04:37.549+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=extract, execution_date=20250218T190433, start_date=20250218T190435, end_date=20250218T190437
[2025-02-18T19:04:37.607+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-02-18T19:04:37.658+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
